framework:
    messenger:
        transports:
            UserListAPI.Labor: "%env(UserListAPI_Labor)%"
            UserListAPI.TestCentrum: "%env(UserListAPI_TestCentrum)%"

        routing:
            'MessageInfo\UserListAPIDataProvider' :
                - UserListAPI.Labor
                - UserListAPI.TestCentrum
